const handleError = err => {
    console.log(err);
    process.exit(1);
};

module.exports = handleError;
